import type { Course, Review } from '@/types';

// Helper
const d = (daysAgo = 0) => new Date(Date.now() - 86400000 * daysAgo).toISOString();
const lessons = (moduleId: string, items: { title: string; type?: 'video' | 'quiz' | 'assignment'; mins?: number; preview?: boolean }[]) =>
  items.map((it, i) => ({
    id: `${moduleId}-l${i + 1}`,
    title: it.title,
    type: (it.type ?? 'video') as 'video' | 'quiz' | 'assignment',
    duration: it.mins ?? 12,
    isPreview: it.preview ?? i === 0,
    order: i + 1,
  }));

export const MOCK_COURSES: Course[] = [
  /* ────────────────────────── MUSIC – Guitar ─────────────────────── */
  {
    id: 'course-guitar-101',
    title: 'Guitar Foundations Bootcamp',
    description: 'A structured beginner-to-intermediate path focused on rhythm, chords, timing, and song building with weekly practice milestones.',
    shortDescription: 'Build strong rhythm and chord confidence in 4 weeks.',
    thumbnail: '',
    category: 'music',
    subcategory: 'guitar',
    level: 'beginner',
    language: 'English',
    price: 1499,
    originalPrice: 2999,
    instructor: { id: 'inst-1', name: 'James Wilson', rating: 4.9 },
    rating: 4.9,
    totalReviews: 832,
    totalStudents: 12420,
    totalLessons: 36,
    totalDuration: 540,
    modules: [
      { id: 'm1', title: 'Setup and Core Basics', order: 1, lessons: lessons('m1', [{ title: 'Welcome & Guitar Setup', preview: true }, { title: 'Hand Position & Posture' }, { title: 'First Chords (C, G, D)', type: 'assignment' }]) },
      { id: 'm2', title: 'Rhythm & Song Building', order: 2, lessons: lessons('m2', [{ title: 'Strumming Patterns', mins: 14 }, { title: 'Chord Transitions', mins: 15 }, { title: 'Performance Check', type: 'quiz', mins: 8 }]) },
    ],
    tags: ['guitar', 'music', 'beginner', 'chords'],
    isPublished: true, isFeatured: true, createdAt: d(90), updatedAt: d(5),
  },

  /* ────────────────────────── MUSIC – Tabla ──────────────────────── */
  {
    id: 'course-tabla-101',
    title: 'Tabla for Beginners',
    description: 'Learn the fundamentals of Indian classical percussion — proper hand technique, basic bols (syllables), taals, and rhythmic cycles used in Hindustani music.',
    shortDescription: 'Master Indian rhythm from the ground up with expert guidance.',
    thumbnail: '',
    category: 'music',
    subcategory: 'tabla',
    level: 'beginner',
    language: 'Hindi',
    price: 1299,
    originalPrice: 2499,
    instructor: { id: 'inst-4', name: 'Pandit Rajan Misra', rating: 4.9 },
    rating: 4.9,
    totalReviews: 612,
    totalStudents: 9800,
    totalLessons: 30,
    totalDuration: 480,
    modules: [
      { id: 'm1', title: 'Tabla Anatomy & Hand Position', order: 1, lessons: lessons('m1', [{ title: 'Introduction to Tabla', preview: true }, { title: 'Finger Placement', mins: 14 }, { title: 'First Bols: Na, Tin, Tun', mins: 15 }]) },
      { id: 'm2', title: 'Teen Taal Foundation', order: 2, lessons: lessons('m2', [{ title: 'Teen Taal Beats 1–8', mins: 16 }, { title: 'Kaida & Variations', mins: 18 }, { title: 'Practice Taal Quiz', type: 'quiz', mins: 10 }]) },
    ],
    tags: ['tabla', 'percussion', 'Hindustani', 'Indian classical'],
    isPublished: true, isFeatured: true, createdAt: d(60), updatedAt: d(3),
  },

  /* ────────────────────────── MUSIC – Flute / Bansuri ──────────── */
  {
    id: 'course-bansuri-101',
    title: 'Bansuri Flute: Indian Classical',
    description: 'A step-by-step journey into the world of the bamboo flute — learn embouchure, breath control, ragas, and classical melodies from Karnataka and Hindustani traditions.',
    shortDescription: 'Play soulful Bansuri melodies with proper breath control.',
    thumbnail: '',
    category: 'music',
    subcategory: 'bansuri',
    level: 'beginner',
    language: 'Hindi',
    price: 999,
    originalPrice: 1999,
    instructor: { id: 'inst-5', name: 'Shri Hari Prasad', rating: 4.8 },
    rating: 4.8,
    totalReviews: 543,
    totalStudents: 7320,
    totalLessons: 28,
    totalDuration: 420,
    modules: [
      { id: 'm1', title: 'Embouchure & Breath Basics', order: 1, lessons: lessons('m1', [{ title: 'Choosing Your Bansuri', preview: true }, { title: 'Producing Pure Notes', mins: 14 }, { title: 'Scale Sa Re Ga Ma', mins: 16 }]) },
      { id: 'm2', title: 'Ragas & Melodies', order: 2, lessons: lessons('m2', [{ title: 'Raga Yaman Foundations', mins: 18 }, { title: 'Simple Alaap', mins: 16 }, { title: 'Bhairavi Composition', type: 'assignment', mins: 15 }]) },
    ],
    tags: ['bansuri', 'flute', 'Indian classical', 'ragas'],
    isPublished: true, isFeatured: true, createdAt: d(45), updatedAt: d(4),
  },

  /* ────────────────────────── MUSIC – Sitar ──────────────────────── */
  {
    id: 'course-sitar-101',
    title: 'Sitar: Start to Solo',
    description: 'Explore the iconic seven-stringed instrument with an emphasis on posture, meend (glides), ragas, and traditional compositions of Indian classical music.',
    shortDescription: 'Learn sitar from scratch with proper raga technique.',
    thumbnail: '',
    category: 'music',
    subcategory: 'sitar',
    level: 'beginner',
    language: 'English',
    price: 1799,
    originalPrice: 3499,
    instructor: { id: 'inst-6', name: 'Ustad Shahid Parvez', rating: 5.0 },
    rating: 5.0,
    totalReviews: 890,
    totalStudents: 14200,
    totalLessons: 42,
    totalDuration: 630,
    modules: [
      { id: 'm1', title: 'Sitar Posture & Strings', order: 1, lessons: lessons('m1', [{ title: 'Holding the Sitar', preview: true }, { title: 'Sa Pa Tuning', mins: 12 }, { title: 'Basic Exercises: Da, Ra', mins: 15 }]) },
      { id: 'm2', title: 'Raga Bhairavi & Yaman', order: 2, lessons: lessons('m2', [{ title: 'Raga Bhairavi Alaap', mins: 20 }, { title: 'Composition Practice', mins: 18 }, { title: 'Solo Performance', type: 'assignment', mins: 20 }]) },
    ],
    tags: ['sitar', 'Indian classical', 'raga', 'string'],
    isPublished: true, isFeatured: false, createdAt: d(30), updatedAt: d(2),
  },

  /* ────────────────────────── MUSIC – Violin ─────────────────────── */
  {
    id: 'course-violin-101',
    title: 'Violin for Beginners',
    description: 'Learn proper bow hold, finger placement, posture, and progress through scales to easy melodies — suitable for both Western and Carnatic violin traditions.',
    shortDescription: 'Beautiful beginnings with the violin — classical or Carnatic.',
    thumbnail: '',
    category: 'music',
    subcategory: 'violin',
    level: 'beginner',
    language: 'English',
    price: 1599,
    originalPrice: 3199,
    instructor: { id: 'inst-7', name: 'Lakshminarayanan K.', rating: 4.8 },
    rating: 4.8,
    totalReviews: 421,
    totalStudents: 6810,
    totalLessons: 32,
    totalDuration: 480,
    modules: [
      { id: 'm1', title: 'Bow & Strings Fundamentals', order: 1, lessons: lessons('m1', [{ title: 'Setup & Tuning', preview: true }, { title: 'Bow Technique', mins: 14 }, { title: 'Open String Exercises', mins: 12 }]) },
      { id: 'm2', title: 'Scales & Simple Melodies', order: 2, lessons: lessons('m2', [{ title: 'G Major Scale', mins: 14 }, { title: 'D Major Scale', mins: 14 }, { title: 'Melody Assignment', type: 'assignment', mins: 12 }]) },
    ],
    tags: ['violin', 'classical', 'Carnatic', 'string'],
    isPublished: true, isFeatured: false, createdAt: d(40), updatedAt: d(6),
  },

  /* ─────────────────────────  MUSIC – Harmonium ──────────────────── */
  {
    id: 'course-harmonium-101',
    title: 'Harmonium: Bhajan & Classical',
    description: 'Learn harmonium from scratch — keyboard basics, scale practice, bhajans, film songs, and light classical accompaniment ideal for spiritual musicians.',
    shortDescription: 'Play beautiful bhajans and classical pieces on harmonium.',
    thumbnail: '',
    category: 'music',
    subcategory: 'harmonium',
    level: 'beginner',
    language: 'Hindi',
    price: 799,
    originalPrice: 1599,
    instructor: { id: 'inst-8', name: 'Vidushi Kalyani Menon', rating: 4.7 },
    rating: 4.7,
    totalReviews: 328,
    totalStudents: 5430,
    totalLessons: 24,
    totalDuration: 360,
    modules: [
      { id: 'm1', title: 'Keys & Bellows Basics', order: 1, lessons: lessons('m1', [{ title: 'Harmonium Overview', preview: true }, { title: 'Scales Sa Re Ga', mins: 12 }, { title: 'Simple Bhajan Melody', mins: 15 }]) },
      { id: 'm2', title: 'Sa Ri Ga Style Exercises', order: 2, lessons: lessons('m2', [{ title: 'Raga Bhupali', mins: 16 }, { title: 'Bhajan: Om Jai Jagdish', mins: 18 }, { title: 'Accompaniment Quiz', type: 'quiz', mins: 8 }]) },
    ],
    tags: ['harmonium', 'bhajan', 'Hindustani', 'keyboard'],
    isPublished: true, isFeatured: false, createdAt: d(55), updatedAt: d(7),
  },

  /* ────────────────────────── MUSIC – Piano ──────────────────────── */
  {
    id: 'course-piano-101',
    title: 'Piano: From Zero to Hero',
    description: 'A comprehensive piano course covering scales, chords, sight-reading, classical pieces, and modern songs — from your very first note to impressive repertoire.',
    shortDescription: 'Play classical and modern songs on piano within weeks.',
    thumbnail: '',
    category: 'music',
    subcategory: 'piano',
    level: 'beginner',
    language: 'English',
    price: 1999,
    originalPrice: 3999,
    instructor: { id: 'inst-9', name: 'Michael Chen', rating: 5.0 },
    rating: 5.0,
    totalReviews: 1203,
    totalStudents: 18900,
    totalLessons: 64,
    totalDuration: 960,
    modules: [
      { id: 'm1', title: 'Piano Basics', order: 1, lessons: lessons('m1', [{ title: 'Keyboard Layout & Posture', preview: true }, { title: 'C Major Scale', mins: 14 }, { title: 'Simple Melody Practice', mins: 12 }]) },
      { id: 'm2', title: 'Chords & Harmony', order: 2, lessons: lessons('m2', [{ title: 'Basic Chords C, F, G', mins: 16 }, { title: 'Left Hand Bass Patterns', mins: 14 }, { title: 'Song Assignment', type: 'assignment', mins: 20 }]) },
    ],
    tags: ['piano', 'keyboard', 'classical', 'Western'],
    isPublished: true, isFeatured: true, createdAt: d(120), updatedAt: d(2),
  },

  /* ────────────────────────── MUSIC – Mridangam ──────────────────── */
  {
    id: 'course-mridangam-101',
    title: 'Mridangam Fundamentals',
    description: 'Learn the Carnatic percussion instrument from the basics — fundamental strokes, adi talam, trikalam speeds, and compositions used in classical concerts.',
    shortDescription: 'Master the Carnatic mridangam with expert instruction.',
    thumbnail: '',
    category: 'music',
    subcategory: 'mridangam',
    level: 'beginner',
    language: 'Tamil',
    price: 1199,
    originalPrice: 2399,
    instructor: { id: 'inst-10', name: 'Karaikudi Mani', rating: 4.9 },
    rating: 4.9,
    totalReviews: 389,
    totalStudents: 5920,
    totalLessons: 26,
    totalDuration: 390,
    modules: [
      { id: 'm1', title: 'Basic Strokes & Adi Talam', order: 1, lessons: lessons('m1', [{ title: 'Introduction to Mridangam', preview: true }, { title: 'Nam & Dhim Strokes', mins: 14 }, { title: 'Adi Talam Pattern', mins: 16 }]) },
      { id: 'm2', title: 'Korvai & Compositions', order: 2, lessons: lessons('m2', [{ title: 'Trikalam Exercise', mins: 18 }, { title: 'Simple Korvai', mins: 16 }, { title: 'Performance Check', type: 'quiz', mins: 10 }]) },
    ],
    tags: ['mridangam', 'Carnatic', 'percussion', 'tala'],
    isPublished: true, isFeatured: false, createdAt: d(35), updatedAt: d(5),
  },

  /* ────────────────────────── MUSIC – Drums ──────────────────────── */
  {
    id: 'course-drums-101',
    title: 'Modern Drumming Masterclass',
    description: 'From basic beats to complex fills — develop your groove, timing, and technique on a drum kit with exercises used by professional session drummers.',
    shortDescription: 'Develop rock-solid timing and professional drumming chops.',
    thumbnail: '',
    category: 'music',
    subcategory: 'drums',
    level: 'beginner',
    language: 'English',
    price: 1399,
    originalPrice: 2799,
    instructor: { id: 'inst-11', name: 'Derek Roddy', rating: 4.8 },
    rating: 4.8,
    totalReviews: 562,
    totalStudents: 9110,
    totalLessons: 34,
    totalDuration: 510,
    modules: [
      { id: 'm1', title: 'Sticking & Basic Beats', order: 1, lessons: lessons('m1', [{ title: 'Grip & Posture', preview: true }, { title: 'Basic Rock Beat', mins: 12 }, { title: 'Four-on-Floor Groove', mins: 14 }]) },
      { id: 'm2', title: 'Fills & Dynamics', order: 2, lessons: lessons('m2', [{ title: 'Quarter Note Fills', mins: 14 }, { title: 'Accents & Ghost Notes', mins: 15 }, { title: 'Groove Assignment', type: 'assignment', mins: 12 }]) },
    ],
    tags: ['drums', 'percussion', 'modern', 'rock'],
    isPublished: true, isFeatured: false, createdAt: d(28), updatedAt: d(4),
  },

  /* ────────────────────────── DANCE – Hip Hop ────────────────────── */
  {
    id: 'course-dance-201',
    title: 'Hip Hop Dance Starter',
    description: 'Learn grooves, isolations, and choreography building with guided drills and performance feedback checkpoints — brought alive with iconic music tracks.',
    shortDescription: 'Master core hip hop moves with weekly choreography practice.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'hip-hop',
    level: 'beginner',
    language: 'English',
    price: 999,
    originalPrice: 1999,
    instructor: { id: 'inst-2', name: 'Priya Sharma', rating: 4.8 },
    rating: 4.8,
    totalReviews: 531,
    totalStudents: 8920,
    totalLessons: 24,
    totalDuration: 420,
    modules: [
      { id: 'm1', title: 'Foundational Movement', order: 1, lessons: lessons('m1', [{ title: 'Warmup & Groove', preview: true }, { title: 'Footwork Patterns', mins: 16 }, { title: 'Top Rock Moves', mins: 14 }]) },
      { id: 'm2', title: 'Choreography Sequence', order: 2, lessons: lessons('m2', [{ title: 'Freestyle Section 1', mins: 14 }, { title: 'Full Routine', mins: 18 }, { title: 'Video Submission', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['dance', 'hip-hop', 'beginner', 'groove'],
    isPublished: true, isFeatured: true, createdAt: d(80), updatedAt: d(6),
  },

  /* ────────────────────────── DANCE – Bharatanatyam ─────────────── */
  {
    id: 'course-bharatanatyam-101',
    title: 'Bharatanatyam Foundations',
    description: 'Begin your Bharatanatyam journey — learn the Namaskar, Araimandi (half-sit), basic adavus (steps), hand gestures (mudras), and simple alarippu composition.',
    shortDescription: 'Learn the ancient classical dance of Tamil Nadu from scratch.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'bharatanatyam',
    level: 'beginner',
    language: 'Tamil',
    price: 1299,
    originalPrice: 2499,
    instructor: { id: 'inst-12', name: 'Savitha Narayanan', rating: 4.9 },
    rating: 4.9,
    totalReviews: 748,
    totalStudents: 11230,
    totalLessons: 36,
    totalDuration: 540,
    modules: [
      { id: 'm1', title: 'Posture & Basic Adavus', order: 1, lessons: lessons('m1', [{ title: 'Namaskar & Araimandi', preview: true }, { title: 'Tatta Adavu Series', mins: 16 }, { title: 'Hand Gestures (Mudras)', mins: 14 }]) },
      { id: 'm2', title: 'Alarippu & Jathis', order: 2, lessons: lessons('m2', [{ title: 'Adi Talam Beats', mins: 14 }, { title: 'Alarippu Full Composition', mins: 18 }, { title: 'Recital Check', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['Bharatanatyam', 'Indian classical dance', 'mudras', 'Tamil Nadu'],
    isPublished: true, isFeatured: true, createdAt: d(50), updatedAt: d(3),
  },

  /* ────────────────────────── DANCE – Kathak ─────────────────────── */
  {
    id: 'course-kathak-101',
    title: 'Kathak Dance: North Indian Classical',
    description: 'Discover the storytelling dance form of North India — spins (chakkars), footwork (tatkar), hand movements, and compositions in both Jaipur and Lucknow gharanas.',
    shortDescription: 'Learn spins, tatkar, and graceful Kathak movements.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'kathak',
    level: 'beginner',
    language: 'Hindi',
    price: 1199,
    originalPrice: 2399,
    instructor: { id: 'inst-13', name: 'Birju Maharaj Jr.', rating: 4.9 },
    rating: 4.9,
    totalReviews: 682,
    totalStudents: 10450,
    totalLessons: 32,
    totalDuration: 480,
    modules: [
      { id: 'm1', title: 'Tatkar & Basic Chakkar', order: 1, lessons: lessons('m1', [{ title: 'Kathak Posture & Namaskar', preview: true }, { title: 'Tatkar in Teen Taal', mins: 16 }, { title: 'First Chakkar (Spin)', mins: 14 }]) },
      { id: 'm2', title: 'Thumri & Compositions', order: 2, lessons: lessons('m2', [{ title: 'Hand & Eye Coordination', mins: 16 }, { title: 'Simple Thumri Piece', mins: 20 }, { title: 'Solo Performance', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['Kathak', 'North Indian', 'classical dance', 'chakkar'],
    isPublished: true, isFeatured: false, createdAt: d(42), updatedAt: d(5),
  },

  /* ────────────────────────── DANCE – Bhangra ────────────────────── */
  {
    id: 'course-bhangra-101',
    title: 'Bhangra: Punjab Folk Dance',
    description: 'High-energy Bhangra — learn signature lunggi turns, arms and shoulder movements, basic boli chants, and build a full Bhangra group sequence.',
    shortDescription: 'Learn joyful Bhangra movements and full group choreography.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'bhangra',
    level: 'beginner',
    language: 'Hindi',
    price: 799,
    originalPrice: 1599,
    instructor: { id: 'inst-14', name: 'Gurbani Judge', rating: 4.7 },
    rating: 4.7,
    totalReviews: 412,
    totalStudents: 6620,
    totalLessons: 20,
    totalDuration: 300,
    modules: [
      { id: 'm1', title: 'Basic Steps & Dhol Beat', order: 1, lessons: lessons('m1', [{ title: 'Warming Up Punjabi Style', preview: true }, { title: 'Lunggi Turn & Arm Raises', mins: 14 }, { title: 'Dhol Pattern & Movement', mins: 12 }]) },
      { id: 'm2', title: 'Group Sequence', order: 2, lessons: lessons('m2', [{ title: 'Bhangra Formation Patterns', mins: 16 }, { title: 'Full Choreography', mins: 20 }, { title: 'Performance Recording', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['Bhangra', 'Punjabi', 'folk dance', 'energetic'],
    isPublished: true, isFeatured: false, createdAt: d(38), updatedAt: d(4),
  },

  /* ────────────────────────── DANCE – Garba ──────────────────────── */
  {
    id: 'course-garba-101',
    title: 'Garba & Dandiya Raas',
    description: 'Celebrate Navratri every day — learn dodhiyu, teen tali, haste-jhanpe steps, circle formations, and Dandiya stick coordination in this high-energy Gujarati folk dance.',
    shortDescription: 'Learn the joyful Garba and Dandiya dances of Gujarat.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'garba',
    level: 'beginner',
    language: 'Gujarati',
    price: 699,
    originalPrice: 1399,
    instructor: { id: 'inst-15', name: 'Rekha Trivedi', rating: 4.6 },
    rating: 4.6,
    totalReviews: 298,
    totalStudents: 4820,
    totalLessons: 18,
    totalDuration: 270,
    modules: [
      { id: 'm1', title: 'Garba Steps & Circles', order: 1, lessons: lessons('m1', [{ title: 'Basic Dodhiyu Step', preview: true }, { title: 'Teen Tali Pattern', mins: 12 }, { title: 'Circle Formation', mins: 14 }]) },
      { id: 'm2', title: 'Dandiya Raas', order: 2, lessons: lessons('m2', [{ title: 'Stick Coordination Basics', mins: 14 }, { title: 'Full Dandiya Sequence', mins: 18 }, { title: 'Celebration Performance', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['Garba', 'Dandiya', 'Gujarat', 'folk dance', 'Navratri'],
    isPublished: true, isFeatured: false, createdAt: d(33), updatedAt: d(6),
  },

  /* ────────────────────────── DANCE – Contemporary ───────────────── */
  {
    id: 'course-contemporary-101',
    title: 'Contemporary Dance: Fluid & Expressive',
    description: 'Explore the freedom of contemporary dance — floor work, improvisation, weight sharing, contact work, and creating your own movement vocabulary.',
    shortDescription: 'Express yourself through contemporary and modern dance.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'contemporary',
    level: 'intermediate',
    language: 'English',
    price: 1099,
    originalPrice: 2199,
    instructor: { id: 'inst-16', name: 'Ananya Prakash', rating: 4.8 },
    rating: 4.8,
    totalReviews: 421,
    totalStudents: 6980,
    totalLessons: 28,
    totalDuration: 420,
    modules: [
      { id: 'm1', title: 'Body & Space Awareness', order: 1, lessons: lessons('m1', [{ title: 'Somatic Warmup', preview: true }, { title: 'Floor Work Basics', mins: 16 }, { title: 'Weight Sharing', mins: 14 }]) },
      { id: 'm2', title: 'Improvisation & Composition', order: 2, lessons: lessons('m2', [{ title: 'Improvisation Scores', mins: 18 }, { title: 'Creating Your Solo', mins: 20 }, { title: 'Solo Showcase', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['contemporary', 'modern dance', 'improvisation', 'expressive'],
    isPublished: true, isFeatured: false, createdAt: d(25), updatedAt: d(3),
  },

  /* ────────────────────────── DANCE – Bollywood ──────────────────── */
  {
    id: 'course-bollywood-101',
    title: 'Bollywood Dance: Filmi Moves',
    description: 'Master Bollywood choreography with a blend of classical mudras, folk steps, and contemporary moves — learn iconic film sequences and create your own style.',
    shortDescription: 'Learn Bollywood moves from actual film choreographies.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'bollywood',
    level: 'beginner',
    language: 'Hindi',
    price: 899,
    originalPrice: 1799,
    instructor: { id: 'inst-17', name: 'Geeta Kapur', rating: 4.7 },
    rating: 4.7,
    totalReviews: 521,
    totalStudents: 8420,
    totalLessons: 22,
    totalDuration: 330,
    modules: [
      { id: 'm1', title: 'Bollywood Basics', order: 1, lessons: lessons('m1', [{ title: 'Energy & Expressions', preview: true }, { title: 'Signature Moves Compilation', mins: 14 }, { title: 'First Sequence', mins: 16 }]) },
      { id: 'm2', title: 'Full Song Choreography', order: 2, lessons: lessons('m2', [{ title: 'Song Selection Tips', mins: 10 }, { title: 'Full Choreography Practice', mins: 22 }, { title: 'Dance Video Submission', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['Bollywood', 'Hindi film', 'dance', 'choreography'],
    isPublished: true, isFeatured: true, createdAt: d(18), updatedAt: d(2),
  },

  /* ────────────────────────── DANCE – Salsa ──────────────────────── */
  {
    id: 'course-salsa-101',
    title: 'Salsa & Latin Dance Basics',
    description: 'Learn the sensual and social dance of Latin America — on1/on2 timing, basic steps, partner connection, turns, and how to social dance confidently.',
    shortDescription: 'Dance Salsa with confidence — solo and with partners.',
    thumbnail: '',
    category: 'dance',
    subcategory: 'salsa',
    level: 'beginner',
    language: 'English',
    price: 999,
    originalPrice: 1999,
    instructor: { id: 'inst-18', name: 'Carlos Lopez', rating: 4.8 },
    rating: 4.8,
    totalReviews: 398,
    totalStudents: 6540,
    totalLessons: 24,
    totalDuration: 360,
    modules: [
      { id: 'm1', title: 'Salsa Basic & Timing', order: 1, lessons: lessons('m1', [{ title: 'Latin Timing & Footwork', preview: true }, { title: 'Basic Step on-1', mins: 14 }, { title: 'Cross Body Lead', mins: 15 }]) },
      { id: 'm2', title: 'Turns & Partner Work', order: 2, lessons: lessons('m2', [{ title: 'Right Turn Basics', mins: 14 }, { title: 'Social Dance Practice', mins: 18 }, { title: 'Salsa Sequence', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['salsa', 'Latin', 'partner dance', 'social dance'],
    isPublished: true, isFeatured: false, createdAt: d(22), updatedAt: d(4),
  },

  /* ────────────────────────── VOCALS – Hindustani Classical ─────── */
  {
    id: 'course-hindustani-101',
    title: 'Hindustani Classical Vocals',
    description: 'Embark on the path of North Indian classical singing — learn sargam, alankars, bandishes in khayal and thumri styles, with guidance from experienced gurukul tradition.',
    shortDescription: 'Learn the deep art of Hindustani classical singing.',
    thumbnail: '',
    category: 'vocals',
    subcategory: 'hindustani',
    level: 'beginner',
    language: 'Hindi',
    price: 1499,
    originalPrice: 2999,
    instructor: { id: 'inst-19', name: 'Pt. Jasraj Das', rating: 5.0 },
    rating: 5.0,
    totalReviews: 934,
    totalStudents: 15800,
    totalLessons: 42,
    totalDuration: 630,
    modules: [
      { id: 'm1', title: 'Sargam & Sur Shuddhata', order: 1, lessons: lessons('m1', [{ title: 'Introduction to Sur & Taal', preview: true }, { title: 'Sargam Practice Sa Re Ga', mins: 14 }, { title: 'Alankar Set 1–5', mins: 16 }]) },
      { id: 'm2', title: 'Ragas & Bandish', order: 2, lessons: lessons('m2', [{ title: 'Raga Bhairav Alaap', mins: 18 }, { title: 'Simple Khayal Bandish', mins: 20 }, { title: 'Recorded Riyaz Check', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['Hindustani', 'classical vocals', 'raga', 'khayal'],
    isPublished: true, isFeatured: true, createdAt: d(70), updatedAt: d(3),
  },

  /* ────────────────────────── VOCALS – Carnatic Classical ────────── */
  {
    id: 'course-carnatic-vocals-101',
    title: 'Carnatic Classical Vocals',
    description: 'Learn the South Indian classical vocal tradition — sarali varisai, geethams, varnams, and kritis in strict swara shuddhata with gamaka techniques.',
    shortDescription: 'Master South Indian classical singing with authentic technique.',
    thumbnail: '',
    category: 'vocals',
    subcategory: 'carnatic-vocal',
    level: 'beginner',
    language: 'Tamil',
    price: 1399,
    originalPrice: 2799,
    instructor: { id: 'inst-20', name: 'Sudha Ragunathan', rating: 4.9 },
    rating: 4.9,
    totalReviews: 728,
    totalStudents: 12100,
    totalLessons: 38,
    totalDuration: 570,
    modules: [
      { id: 'm1', title: 'Sarali & Swara Shuddhata', order: 1, lessons: lessons('m1', [{ title: 'Introduction to Shruti', preview: true }, { title: 'Sarali Varisai Set 1–4', mins: 14 }, { title: 'Janta Varisai Practice', mins: 16 }]) },
      { id: 'm2', title: 'Geethams & Varnams', order: 2, lessons: lessons('m2', [{ title: 'Geetham: Lambodara', mins: 16 }, { title: 'Simple Varnam', mins: 20 }, { title: 'Shruti Matching Check', type: 'quiz', mins: 10 }]) },
    ],
    tags: ['Carnatic', 'classical vocals', 'South Indian', 'swara'],
    isPublished: true, isFeatured: true, createdAt: d(60), updatedAt: d(4),
  },

  /* ────────────────────────── VOCALS – Ghazal ────────────────────── */
  {
    id: 'course-ghazal-101',
    title: 'Ghazal Singing: Urdu Poetry & Music',
    description: 'Explore the delicate art of Ghazal — learn the maqta, radif, qafia, appropriate ragas for ghazals, and perform with tarang in the style of great ustads.',
    shortDescription: 'Sing Ghazals with poetry appreciation and classical nuance.',
    thumbnail: '',
    category: 'vocals',
    subcategory: 'ghazal',
    level: 'intermediate',
    language: 'Hindi',
    price: 1299,
    originalPrice: 2499,
    instructor: { id: 'inst-21', name: 'Hariharan Ji', rating: 4.9 },
    rating: 4.9,
    totalReviews: 582,
    totalStudents: 9430,
    totalLessons: 30,
    totalDuration: 450,
    modules: [
      { id: 'm1', title: 'Urdu Poetry & Pronunciation', order: 1, lessons: lessons('m1', [{ title: 'Ghazal Structure & Maqta', preview: true }, { title: 'Urdu Makharij Basics', mins: 14 }, { title: 'First Ghazal: Hazaron Khwahishen', mins: 18 }]) },
      { id: 'm2', title: 'Raga Ghazals', order: 2, lessons: lessons('m2', [{ title: 'Raga Yaman Ghazal', mins: 18 }, { title: 'Live Mehfil Style', mins: 20 }, { title: 'Recorded Ghazal', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['ghazal', 'Urdu', 'semi-classical', 'vocals'],
    isPublished: true, isFeatured: false, createdAt: d(48), updatedAt: d(5),
  },

  /* ────────────────────────── VOCALS – Western Pop ───────────────── */
  {
    id: 'course-western-pop-101',
    title: 'Western Pop & Contemporary Vocals',
    description: 'Develop your modern singing voice — learn chest and head voice mix, belting, vibrato, runs and riffs, mic technique, and performance delivery for pop music.',
    shortDescription: 'Sing pop, R&B, and modern music with professional technique.',
    thumbnail: '',
    category: 'vocals',
    subcategory: 'western-pop',
    level: 'beginner',
    language: 'English',
    price: 1199,
    originalPrice: 2399,
    instructor: { id: 'inst-22', name: 'Neha Kakkar Pro', rating: 4.7 },
    rating: 4.7,
    totalReviews: 811,
    totalStudents: 13400,
    totalLessons: 34,
    totalDuration: 510,
    modules: [
      { id: 'm1', title: 'Voice Foundation', order: 1, lessons: lessons('m1', [{ title: 'Breath Support & Posture', preview: true }, { title: 'Chest vs. Head Voice', mins: 14 }, { title: 'Bridge & Mix Voice', mins: 16 }]) },
      { id: 'm2', title: 'Pop Techniques', order: 2, lessons: lessons('m2', [{ title: 'Belting Safely', mins: 16 }, { title: 'Runs & Riffs 101', mins: 18 }, { title: 'Original Song Recording', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['western pop', 'vocals', 'belting', 'R&B'],
    isPublished: true, isFeatured: false, createdAt: d(32), updatedAt: d(3),
  },

  /* ────────────────────────── VOCALS – Sufi ──────────────────────── */
  {
    id: 'course-sufi-101',
    title: 'Sufi Music & Qawwali Vocals',
    description: 'Journey into the mystical world of Sufi music — learn the kafi style, layakari, qawwali call-and-response, and compositions of Amir Khusro and contemporary Sufi masters.',
    shortDescription: 'Explore the spiritual depth of Sufi and Qawwali singing.',
    thumbnail: '',
    category: 'vocals',
    subcategory: 'sufi',
    level: 'intermediate',
    language: 'Hindi',
    price: 999,
    originalPrice: 1999,
    instructor: { id: 'inst-23', name: 'Wadali Brothers Lineage', rating: 4.8 },
    rating: 4.8,
    totalReviews: 431,
    totalStudents: 7020,
    totalLessons: 24,
    totalDuration: 360,
    modules: [
      { id: 'm1', title: 'Sufi Tradition & Kafi', order: 1, lessons: lessons('m1', [{ title: 'History of Sufi Music', preview: true }, { title: 'Kafi Style Introduction', mins: 14 }, { title: 'Amir Khusro Composition', mins: 18 }]) },
      { id: 'm2', title: 'Qawwali Techniques', order: 2, lessons: lessons('m2', [{ title: 'Call & Response Patterns', mins: 16 }, { title: 'Layakari Practice', mins: 18 }, { title: 'Qawwali Performance', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['sufi', 'qawwali', 'spiritual', 'Urdu'],
    isPublished: true, isFeatured: false, createdAt: d(26), updatedAt: d(4),
  },

  /* ────────────────────────── VOCALS – Playback Singing ───────────── */
  {
    id: 'course-playback-101',
    title: 'Playback Singing: Filmi Style',
    description: 'Learn to sing like your favorite Bollywood singers — mic technique, diction, emotional coloring, and how to match your voice to film compositions across genres.',
    shortDescription: 'Sing Bollywood playback with professional studio technique.',
    thumbnail: '',
    category: 'vocals',
    subcategory: 'playback',
    level: 'intermediate',
    language: 'Hindi',
    price: 1299,
    originalPrice: 2599,
    instructor: { id: 'inst-24', name: 'Shaan Kumar', rating: 4.8 },
    rating: 4.8,
    totalReviews: 721,
    totalStudents: 11980,
    totalLessons: 30,
    totalDuration: 450,
    modules: [
      { id: 'm1', title: 'Diction & Mic Technique', order: 1, lessons: lessons('m1', [{ title: 'Studio Mic Placement', preview: true }, { title: 'Hindi Diction Clarity', mins: 14 }, { title: 'Emotional Colour of Notes', mins: 16 }]) },
      { id: 'm2', title: 'Song Interpretation', order: 2, lessons: lessons('m2', [{ title: 'Sad vs Happy Song Approach', mins: 16 }, { title: 'Recording Cover Song', mins: 20 }, { title: 'Final Studio Track', type: 'assignment', mins: 5 }]) },
    ],
    tags: ['playback', 'Bollywood', 'studio', 'film'],
    isPublished: true, isFeatured: false, createdAt: d(20), updatedAt: d(2),
  },

  /* ────────────────────────── THEATER ────────────────────────────── */
  {
    id: 'course-theater-301',
    title: 'Theater Voice and Presence',
    description: 'Train projection, diction, stage movement, and emotional expression for stage and camera — perfect for actors, presenters, and performers.',
    shortDescription: 'Develop a powerful stage voice and confident performance presence.',
    thumbnail: '',
    category: 'theater',
    subcategory: 'voice',
    level: 'intermediate',
    language: 'English',
    price: 1299,
    originalPrice: 2499,
    instructor: { id: 'inst-3', name: 'Asha Kapoor', rating: 4.7 },
    rating: 4.7,
    totalReviews: 248,
    totalStudents: 3610,
    totalLessons: 18,
    totalDuration: 300,
    modules: [
      { id: 'm1', title: 'Voice Mechanics', order: 1, lessons: lessons('m1', [{ title: 'Breath Support', preview: true }, { title: 'Projection Techniques', mins: 14 }, { title: 'Diction Exercises', mins: 12 }]) },
      { id: 'm2', title: 'Stage Movement & Expression', order: 2, lessons: lessons('m2', [{ title: 'Body Language on Stage', mins: 14 }, { title: 'Emotional Monologue', mins: 18 }, { title: 'Scene Performance', type: 'assignment', mins: 10 }]) },
    ],
    tags: ['theater', 'voice', 'acting', 'stage'],
    isPublished: true, isFeatured: false, createdAt: d(100), updatedAt: d(8),
  },
];

/* ─── Reviews ─────────────────────────────────────────────────────── */
export const MOCK_REVIEWS_BY_COURSE: Record<string, Review[]> = {
  'course-guitar-101': [
    { id: 'rev-1', courseId: 'course-guitar-101', user: { id: 'u-1', name: 'Rahul Mehta' }, rating: 5, comment: 'Excellent sequencing. I was playing complete songs in two weeks!', helpful: 42, createdAt: d(3) },
    { id: 'rev-2', courseId: 'course-guitar-101', user: { id: 'u-2', name: 'Nina Shah' }, rating: 4, comment: 'Great content and very practical assignments.', helpful: 19, createdAt: d(9) },
  ],
  'course-tabla-101': [
    { id: 'rev-3', courseId: 'course-tabla-101', user: { id: 'u-3', name: 'Arjun Singh' }, rating: 5, comment: 'Pandit ji explains every bol with such clarity. Brilliant!', helpful: 38, createdAt: d(5) },
  ],
  'course-bharatanatyam-101': [
    { id: 'rev-4', courseId: 'course-bharatanatyam-101', user: { id: 'u-4', name: 'Kavya Pillai' }, rating: 5, comment: 'Savitha madam\'s teaching is so detailed and patient. Loved every lesson!', helpful: 52, createdAt: d(6) },
  ],
  'course-hindustani-101': [
    { id: 'rev-5', courseId: 'course-hindustani-101', user: { id: 'u-5', name: 'Vikram Gupta' }, rating: 5, comment: 'The riyaz structure is exactly what I needed. Highly recommend!', helpful: 61, createdAt: d(4) },
  ],
};

export function getMockCourseById(id: string): Course | undefined {
  return MOCK_COURSES.find((course) => course.id === id);
}
